name: Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15]
    steps:
    - uses: actions/checkout@v4
    - name: Show versions
      run: sw_vers && xcodebuild -version
    - name: Run Tests
      run: xcodebuild test -scheme Hello -resultBundlePath TestResults.xcresult
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults.xcresult
